import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: "#f5f0e7",
    alignItems: "center",
    paddingTop: 42,
  },
  ehh: {
    flex: 1,
    backgroundColor: "#f5f0e7",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  connection: {
    justifyContent: "center",
    alignItems: "center",
  },
  connectionProblems: {
    color: "#534833",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 0.6,
    fontSize: 18,
    padding: 0,
    margin: 0,
  },
  center: {
    flex: 1,
    alignItems: "center",
    width: "100%",
  },
  container: {
    marginTop: 5,
    width: "90%",
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    justifyContent: "space-around",
  },
  containerbigger: {
    marginTop: 5,
    width: "92.5%",
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    justifyContent: "space-around",
    // elevation: 0,
  },
  containersmaller: {
    marginTop: 5,
    width: "87.5%",
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    justifyContent: "space-around",
    transform: [{ scale: 1 }],
    // opacity: 0.95,
  },
  containersmall: {
    marginTop: 5,
    width: "90%",
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    justifyContent: "space-around",
    transform: [{ scale: 1 }],
    // opacity: 0.95,
  },
  sideContent: {
    paddingVertical: "auto",
    alignItems: "center",
    justifyContent: "center",
    width: 75,
  },
  centerbig: {
    flex: 1,
    height: "auto",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    paddingVertical: 12.5,
    borderColor: "#f5f0e7",
  },
  centersmall: {
    flex: 1,
    height: "auto",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    paddingVertical: 0,
    borderColor: "#f5f0e7",
  },
  beginningHour: {
    color: "#D3CDC3",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 0.6,
    fontSize: 18,
    padding: 0,
    margin: 0,
  },
  beginningHourrep: {
    color: "#ff6961",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 0.6,
    fontSize: 18,
    padding: 0,
    margin: 0,
  },
  endingHour: {
    color: "#D3CDC3",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 0.6,
    fontSize: 14,
    padding: 0,
    margin: 0,
    marginTop: -10,
    opacity: 0.9,
  },
  endingHourrep: {
    color: "#ff6961",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 0.6,
    fontSize: 14,
    padding: 0,
    margin: 0,
    marginTop: -10,
    opacity: 0.9,
  },
  room: {
    color: "#D3CDC3",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    fontSize: 19,
    letterSpacing: 0.5,
    paddingVertical: 1.2,
    paddingHorizontal: 5,
  },
  roomrep: {
    color: "#ff6961",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    fontSize: 19,
    letterSpacing: 0.5,
    paddingVertical: 1.2,
    paddingHorizontal: 5,
  },
  subject: {
    color: "#DBC196",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 1,
    fontSize: 21,
  },
  subjectrep: {
    color: "#ff6961",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 1,
    fontSize: 21,
  },
  textbig: {
    color: "#DBC196",
    fontFamily: "jaapokki-regular",
    fontWeight: "200",
    letterSpacing: 1,
    fontSize: 22,
  },
  scrollBox: {
    width: "100%",
    maxHeight: "97%",
  },
  bottom: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: 0,
    width: "100%",
    maxHeight: "100%",
  },
  pickBox: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    width: "90%",
    marginBottom: 0,
    alignItems: "center",
  },
  arrowButton: {
    paddingVertical: "auto",
    alignItems: "center",
    justifyContent: "center",
    width: 50,
  },
  info: {
    color: "#534833",
    fontFamily: "jaapokki-substract",
    fontWeight: "200",
    letterSpacing: 1,
    fontSize: 32,
  },
  arrow: {
    fontFamily: "jaapokki-regular",
    fontSize: 30,
    color: "#534833",
  },
  top: {
    paddingTop: 10,
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 12,
    width: "95%",
    maxHeight: "15%",
  },
  infoBox: {
    flex: 1,
    height: "auto",
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 0,
    borderBottomWidth: 0,
    paddingVertical: 0,
  },
  bottomer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    maxHeight: "4%",
    width: "100%",
  },
  schoolNameContainer: {
    maxWidth: "70%",
    width: "70%",
    justifyContent: "center",
    paddingLeft: 5,
  },
  schoolHeader: {
    fontFamily: "jaapokki-regular",
    fontWeight: "normal",
    paddingVertical: 0,
    marginVertical: 0,
    fontSize: 18,
  },
  nocon: {
    flex: 1,
    resizeMode: "contain",
    width: 120,
    height: 120,
  },

  schoolName: {
    fontFamily: "jaapokki-regular",
    fontWeight: "normal",
    paddingVertical: 0,
    marginVertical: 0,
    fontSize: 28,
    color: "#534833",
  },
  settings: {
    maxWidth: "30%",
    width: "30%",
  },
  classbtn: {
    backgroundColor: "#CCC4B8",
    // backgroundColor: "#534833",
    opacity: 1,
    borderRadius: 8,
    padding: 8,
    paddingHorizontal: 22,
    margin: 2,
  },
  luckybtn: {
    backgroundColor: "#CCC4B8",
    // backgroundColor: "#534833",
    opacity: 1,
    borderRadius: 8,
    padding: 5.5,
    paddingHorizontal: 13,
  },
  btntxt: {
    color: "#fff",
    fontFamily: "jaapokki-regular",
    fontSize: 18,
  },
  luckytxt: {
    color: "#fff",
    fontFamily: "jaapokki-regular",
    fontSize: 22,
  },
  topagain: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  backdrop: {
    opacity: 0.5,
  },
  overlay: {
    padding: 20,
    margin: 0,
    borderRadius: 10,
    backgroundColor: "#f5f0e7",
    maxHeight: 330,
    width: "90%",
    shadowOpacity: 0,
    elevation: 6,
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  overlayyy: {
    padding: 0,
    margin: 0,
    borderRadius: 10,
    maxHeight: "100%",
    width: "100%",
    shadowOpacity: 0,
    elevation: 0,
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  luckyNumbersContainer: {
    maxHeight: 140,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  luckyNumbersCard: {
    backgroundColor: "white",
    width: 140,
    height: 140,
    maxWidth: 140,
    maxHeight: 140,
    borderRadius: 10,
    margin: 5,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  luckyNumber: {
    color: "#DBC196",
    fontFamily: "jaapokki-regular",
    fontSize: 72,
  },
  bezContainer: {
    padding: 10,
    justifyContent: "center",
    textAlign: "center",
    backgroundColor: "white",
    borderRadius: 5,
    margin: 5,
  },
  bezClass: {
    color: "#D3CDC3",
    fontFamily: "jaapokki-substract",
    fontSize: 18,
    letterSpacing: 0.2,
  },
  bezAll: {
    marginTop: 5,
    flex: 1,
    maxHeight: 45,
    marginBottom: -5,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  bezIndicator: {
    color: "#CCC4B8",
    fontFamily: "jaapokki-regular",
    fontSize: 22,
    letterSpacing: 0.2,
    marginTop: 20,
  },
  numbersIndicator: {
    color: "#534833",
    fontFamily: "jaapokki-regular",
    fontSize: 32,
    letterSpacing: 0.2,
    paddingBottom: 5,
  },
  signature: {
    color: "#534833",
    fontFamily: "jaapokki-regular",
    fontSize: 32,
    letterSpacing: 0.2,
  },
  infolol: {
    color: "#534833",
    fontFamily: "jaapokki-regular",
    fontSize: 18,
    letterSpacing: 0.2,
    marginBottom: 15,
  },
  pickHeaderContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    maxHeight: "10%",
    padding: "auto",
  },
  pickHeaderText: {
    fontFamily: "jaapokki-regular",
    color: "#534833",
    fontSize: 36,
  },
  schoolScrollBox: {
    width: "100%",
    maxHeight: "100%",
    marginTop: 10,
  },
  schoolContainer: {
    backgroundColor: "white",
    width: "90%",
    height: "auto",
    borderRadius: 10,
    marginTop: 5,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingLeft: "5%",
    paddingVertical: 10,
  },
  bottomPick: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: 6,
    width: "100%",
    maxHeight: "85%",
  },
  leftSide: {
    width: "80%",
    paddingRight: "2.5%",
  },
  rightSide: {
    width: "20%",
    borderLeftWidth: 2,
    borderColor: "#f5f0e7",
    height: "100%",
    paddingBottom: 3,
  },
  schoolNameText: {
    color: "#DBC196",
    fontFamily: "jaapokki-regular",
    fontSize: 22,
  },
  pickSchoolBtn: {
    paddingRight: "4%",
    fontSize: 22,
    fontFamily: "jaapokki-regular",
    color: "#534833",
  },
  full: {
    height: "100%",
    width: "100%",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  schoolFillText: {
    fontFamily: "jaapokki-regular",
    fontSize: 18,
    color: "#D3CDC3",
    letterSpacing: 0.25,
  },
  imisplash: {
    maxWidth: "100%",
    maxHeight: "78%",
    resizeMode: "contain",
  },
});

export default styles;
